import { Product, Post, Review } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    creator_id: "c1",
    name: "NeuralVox Pro",
    slug: "neuralvox-pro",
    tagline: "State-of-the-art voice synthesis & cloning engine",
    description: "NeuralVox Pro is the most advanced voice synthesis engine on the market. Clone any voice with just 30 seconds of audio, generate natural speech in 40+ languages, and create custom voice personas for your applications. Used by top content creators, game studios, and accessibility platforms worldwide.",
    category: "Voice & Audio",
    tags: ["Voice Synthesis", "Text-to-Speech", "Voice Cloning"],
    price: 49.99,
    gradient: "from-purple-600 via-violet-600 to-indigo-600",
    accent_color: "#7c5bf5",
    rating: 4.8,
    download_count: 12400,
    api_endpoint: "https://api.nexusai.dev/v1/neuralvox",
    documentation_url: "https://docs.nexusai.dev/neuralvox",
    auth_type: "api_key",
    websocket_support: true,
    version: "3.2.1",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Voice cloning with 30s audio", "40+ language support", "Real-time streaming", "Custom voice personas", "SSML support", "Emotion control"],
    created_at: "2024-08-15",
    updated_at: "2024-12-01",
  },
  {
    id: "2",
    creator_id: "c2",
    name: "PixelForge",
    slug: "pixelforge",
    tagline: "Open-source image generation for everyone",
    description: "PixelForge is a free, open-source image generation model that produces stunning visuals from text prompts. With support for multiple art styles, inpainting, outpainting, and image-to-image transformations, it's the perfect tool for designers, artists, and developers alike.",
    category: "Image Generation",
    tags: ["Image Gen", "Open Source", "Art"],
    price: 0,
    gradient: "from-cyan-500 via-blue-500 to-indigo-500",
    accent_color: "#00d4ff",
    rating: 4.6,
    download_count: 34100,
    api_endpoint: "https://api.nexusai.dev/v1/pixelforge",
    documentation_url: "https://docs.nexusai.dev/pixelforge",
    auth_type: "api_key",
    websocket_support: false,
    version: "2.1.0",
    license: "open-source",
    download_url: "",
    status: "published",
    features: ["Text-to-image generation", "Inpainting & outpainting", "Style transfer", "Image-to-image", "Batch processing", "Custom model training"],
    created_at: "2024-06-20",
    updated_at: "2024-11-15",
  },
  {
    id: "3",
    creator_id: "c3",
    name: "CodePilot X",
    slug: "codepilot-x",
    tagline: "AI pair programmer that actually understands your codebase",
    description: "CodePilot X goes beyond simple code completion. It understands your entire codebase, generates tests, refactors code, and writes documentation. Supports 30+ programming languages with context-aware suggestions that respect your coding style and patterns.",
    category: "Developer Tools",
    tags: ["Code Gen", "Developer", "AI Assistant"],
    price: 29.99,
    gradient: "from-orange-500 via-red-500 to-rose-500",
    accent_color: "#ff6b35",
    rating: 4.9,
    download_count: 45200,
    api_endpoint: "https://api.nexusai.dev/v1/codepilot",
    documentation_url: "https://docs.nexusai.dev/codepilot",
    auth_type: "api_key",
    websocket_support: true,
    version: "4.0.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Full codebase understanding", "30+ language support", "Test generation", "Code refactoring", "Documentation generation", "IDE integrations"],
    created_at: "2024-05-10",
    updated_at: "2024-12-05",
  },
  {
    id: "4",
    creator_id: "c4",
    name: "ChatWeaver",
    slug: "chatweaver",
    tagline: "Build intelligent chatbots in minutes, not months",
    description: "ChatWeaver lets you create sophisticated chatbots with natural conversation flows, memory, and tool use capabilities. Perfect for customer support, sales, education, and internal tools. No ML expertise required.",
    category: "Chatbots",
    tags: ["Chatbot", "Conversational AI", "No-Code"],
    price: 19.99,
    gradient: "from-emerald-500 via-green-500 to-teal-500",
    accent_color: "#10b981",
    rating: 4.5,
    download_count: 8700,
    api_endpoint: "https://api.nexusai.dev/v1/chatweaver",
    documentation_url: "https://docs.nexusai.dev/chatweaver",
    auth_type: "api_key",
    websocket_support: true,
    version: "2.4.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Visual flow builder", "Memory & context", "Tool use integration", "Multi-channel deploy", "Analytics dashboard", "Custom training"],
    created_at: "2024-07-01",
    updated_at: "2024-11-20",
  },
  {
    id: "5",
    creator_id: "c5",
    name: "DataMind",
    slug: "datamind",
    tagline: "Turn raw data into insights with natural language",
    description: "DataMind connects to your databases and data sources, letting you query data with natural language. Generate reports, visualizations, and predictive analytics without writing SQL or Python. Perfect for business analysts and data teams.",
    category: "Data & Analytics",
    tags: ["Analytics", "Data Science", "Business Intelligence"],
    price: 39.99,
    gradient: "from-amber-500 via-yellow-500 to-orange-500",
    accent_color: "#f59e0b",
    rating: 4.7,
    download_count: 5300,
    api_endpoint: "https://api.nexusai.dev/v1/datamind",
    documentation_url: "https://docs.nexusai.dev/datamind",
    auth_type: "oauth",
    websocket_support: false,
    version: "1.8.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Natural language queries", "Auto-visualization", "Predictive analytics", "Database connectors", "Scheduled reports", "Team collaboration"],
    created_at: "2024-09-01",
    updated_at: "2024-11-30",
  },
  {
    id: "6",
    creator_id: "c6",
    name: "TransLingua",
    slug: "translingua",
    tagline: "Free real-time translation across 100+ languages",
    description: "TransLingua provides instant, high-quality translations across 100+ languages with context-aware understanding. Supports document translation, real-time conversation mode, and specialized vocabulary for legal, medical, and technical domains.",
    category: "Language",
    tags: ["Translation", "NLP", "Free"],
    price: 0,
    gradient: "from-pink-500 via-rose-500 to-red-500",
    accent_color: "#ec4899",
    rating: 4.3,
    download_count: 22100,
    api_endpoint: "https://api.nexusai.dev/v1/translingua",
    documentation_url: "https://docs.nexusai.dev/translingua",
    auth_type: "api_key",
    websocket_support: true,
    version: "5.0.0",
    license: "open-source",
    download_url: "",
    status: "published",
    features: ["100+ languages", "Context-aware translation", "Document translation", "Real-time mode", "Domain specialization", "Glossary support"],
    created_at: "2024-03-15",
    updated_at: "2024-10-20",
  },
  {
    id: "7",
    creator_id: "c7",
    name: "MusicForge AI",
    slug: "musicforge-ai",
    tagline: "Generate original music and soundscapes with AI",
    description: "MusicForge AI creates original, royalty-free music from text descriptions. Generate background music, sound effects, jingles, and full compositions in any genre. Perfect for content creators, game developers, and filmmakers.",
    category: "Voice & Audio",
    tags: ["Music Gen", "Audio", "Creative"],
    price: 24.99,
    gradient: "from-violet-500 via-purple-500 to-fuchsia-500",
    accent_color: "#8b5cf6",
    rating: 4.4,
    download_count: 6800,
    api_endpoint: "https://api.nexusai.dev/v1/musicforge",
    documentation_url: "https://docs.nexusai.dev/musicforge",
    auth_type: "api_key",
    websocket_support: false,
    version: "1.5.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Text-to-music generation", "50+ genres", "Sound effects", "Stem separation", "Custom training", "Royalty-free output"],
    created_at: "2024-10-01",
    updated_at: "2024-12-01",
  },
  {
    id: "8",
    creator_id: "c8",
    name: "AgentSmith",
    slug: "agentsmith",
    tagline: "Build autonomous AI agents that get things done",
    description: "AgentSmith is the most powerful agent framework on NexusAI. Build autonomous AI agents that can browse the web, use tools, write code, manage files, and complete complex multi-step tasks. Enterprise-grade reliability with full audit logging.",
    category: "Agents",
    tags: ["Autonomous Agent", "Automation", "Enterprise"],
    price: 59.99,
    gradient: "from-cyan-500 via-teal-500 to-emerald-500",
    accent_color: "#06b6d4",
    rating: 4.8,
    download_count: 3200,
    api_endpoint: "https://api.nexusai.dev/v1/agentsmith",
    documentation_url: "https://docs.nexusai.dev/agentsmith",
    auth_type: "api_key",
    websocket_support: true,
    version: "2.0.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Autonomous task completion", "Web browsing", "Tool use framework", "Multi-step planning", "Audit logging", "Custom tool creation"],
    created_at: "2024-11-01",
    updated_at: "2024-12-10",
  },
  {
    id: "9",
    creator_id: "c9",
    name: "VisionAI Pro",
    slug: "visionai-pro",
    tagline: "Advanced computer vision for any application",
    description: "VisionAI Pro provides state-of-the-art computer vision capabilities including object detection, image segmentation, OCR, facial recognition, and scene understanding. Deploy on edge devices or in the cloud with optimized inference.",
    category: "Computer Vision",
    tags: ["Computer Vision", "Object Detection", "OCR"],
    price: 44.99,
    gradient: "from-red-500 via-rose-500 to-pink-500",
    accent_color: "#ef4444",
    rating: 4.6,
    download_count: 4100,
    api_endpoint: "https://api.nexusai.dev/v1/visionai",
    documentation_url: "https://docs.nexusai.dev/visionai",
    auth_type: "api_key",
    websocket_support: false,
    version: "3.1.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Object detection", "Image segmentation", "OCR engine", "Scene understanding", "Edge deployment", "Real-time processing"],
    created_at: "2024-08-01",
    updated_at: "2024-11-25",
  },
  {
    id: "10",
    creator_id: "c10",
    name: "WriteGenie",
    slug: "writegenie",
    tagline: "AI writing assistant that matches your voice",
    description: "WriteGenie adapts to your unique writing style and helps you create compelling content faster. From blog posts to marketing copy, technical docs to creative fiction. Includes SEO optimization, plagiarism checking, and multi-format export.",
    category: "Writing",
    tags: ["Writing", "Content", "SEO"],
    price: 14.99,
    gradient: "from-sky-500 via-cyan-500 to-teal-500",
    accent_color: "#22d3ee",
    rating: 4.2,
    download_count: 18500,
    api_endpoint: "https://api.nexusai.dev/v1/writegenie",
    documentation_url: "https://docs.nexusai.dev/writegenie",
    auth_type: "api_key",
    websocket_support: false,
    version: "2.3.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Style matching", "SEO optimization", "Plagiarism check", "Multi-format export", "Team collaboration", "Brand voice profiles"],
    created_at: "2024-04-15",
    updated_at: "2024-11-10",
  },
  {
    id: "11",
    creator_id: "c11",
    name: "FinanceBot",
    slug: "financebot",
    tagline: "AI-powered financial analysis and forecasting",
    description: "FinanceBot provides institutional-grade financial analysis powered by AI. Real-time market data analysis, risk assessment, portfolio optimization, and predictive forecasting. Trusted by hedge funds, banks, and financial advisors.",
    category: "Finance",
    tags: ["Finance", "Analytics", "Forecasting"],
    price: 79.99,
    gradient: "from-lime-500 via-green-500 to-emerald-500",
    accent_color: "#84cc16",
    rating: 4.9,
    download_count: 2100,
    api_endpoint: "https://api.nexusai.dev/v1/financebot",
    documentation_url: "https://docs.nexusai.dev/financebot",
    auth_type: "oauth",
    websocket_support: true,
    version: "1.2.0",
    license: "commercial",
    download_url: "",
    status: "published",
    features: ["Real-time analysis", "Risk assessment", "Portfolio optimization", "Predictive forecasting", "Regulatory compliance", "Custom indicators"],
    created_at: "2024-10-15",
    updated_at: "2024-12-08",
  },
  {
    id: "12",
    creator_id: "c12",
    name: "DocuScan AI",
    slug: "docuscan-ai",
    tagline: "Free intelligent document processing and extraction",
    description: "DocuScan AI transforms unstructured documents into structured data. Extract tables, forms, receipts, invoices, and more with high accuracy. Supports 50+ document formats with automatic classification and data validation.",
    category: "Productivity",
    tags: ["Document AI", "OCR", "Free"],
    price: 0,
    gradient: "from-violet-400 via-purple-400 to-indigo-400",
    accent_color: "#a78bfa",
    rating: 4.1,
    download_count: 31700,
    api_endpoint: "https://api.nexusai.dev/v1/docuscan",
    documentation_url: "https://docs.nexusai.dev/docuscan",
    auth_type: "api_key",
    websocket_support: false,
    version: "1.9.0",
    license: "open-source",
    download_url: "",
    status: "published",
    features: ["50+ format support", "Table extraction", "Form recognition", "Auto-classification", "Data validation", "Batch processing"],
    created_at: "2024-07-20",
    updated_at: "2024-11-28",
  },
];

export const mockPosts: Post[] = [
  {
    id: "p1",
    author_id: "admin",
    title: "Getting Started with NexusAI",
    content: "Welcome to NexusAI! This guide covers everything you need to know to get started as a creator or buyer on the platform.",
    category: "general",
    upvotes: 342,
    reply_count: 234,
    pinned: true,
    created_at: "2024-11-01",
    author: { id: "admin", email: "team@nexusai.dev", full_name: "NexusAI Team", avatar_url: "", role: "admin", subscription: "enterprise", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "p2",
    author_id: "u1",
    title: "Best practices for pricing your AI",
    content: "After a year of selling on NexusAI, here are my top tips for pricing your AI products effectively.",
    category: "tips",
    upvotes: 189,
    reply_count: 89,
    pinned: false,
    created_at: "2024-12-05",
    author: { id: "u1", email: "synthminds@email.com", full_name: "SynthMinds AI", avatar_url: "", role: "creator", subscription: "pro", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "p3",
    author_id: "u2",
    title: "How I built a 10K download AI tool",
    content: "My journey from 0 to 10K downloads in 3 months, including marketing strategies and technical decisions.",
    category: "showcase",
    upvotes: 267,
    reply_count: 156,
    pinned: false,
    created_at: "2024-12-08",
    author: { id: "u2", email: "devforge@email.com", full_name: "DevForge", avatar_url: "", role: "creator", subscription: "pro", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "p4",
    author_id: "u3",
    title: "API optimization tips & tricks",
    content: "Advanced techniques for optimizing your AI's API performance, including caching, batching, and streaming.",
    category: "tips",
    upvotes: 145,
    reply_count: 67,
    pinned: false,
    created_at: "2024-12-10",
    author: { id: "u3", email: "opticmind@email.com", full_name: "OpticMind", avatar_url: "", role: "creator", subscription: "pro", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "p5",
    author_id: "u4",
    title: "Showcase: My new image generation model",
    content: "Excited to share my latest image generation model! Check out the samples and let me know what you think.",
    category: "showcase",
    upvotes: 98,
    reply_count: 45,
    pinned: false,
    created_at: "2024-12-12",
    author: { id: "u4", email: "artisanlabs@email.com", full_name: "Artisan Labs", avatar_url: "", role: "creator", subscription: "starter", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "p6",
    author_id: "u5",
    title: "Help: Webhook integration not working",
    content: "I'm trying to set up webhook notifications for my AI product but the callbacks aren't being received. Has anyone dealt with this?",
    category: "help",
    upvotes: 23,
    reply_count: 12,
    pinned: false,
    created_at: "2024-12-14",
    author: { id: "u5", email: "newcreator@email.com", full_name: "NewCreator42", avatar_url: "", role: "creator", subscription: "starter", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    user_id: "ru1",
    product_id: "1",
    rating: 5,
    comment: "Incredible voice quality. The cloning feature is unbelievably accurate with just 30 seconds of audio. Best TTS I've ever used.",
    created_at: "2024-11-20",
    user: { id: "ru1", email: "", full_name: "Jordan Miller", avatar_url: "", role: "buyer", subscription: "free", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "r2",
    user_id: "ru2",
    product_id: "1",
    rating: 5,
    comment: "We integrated NeuralVox into our podcast production workflow and it saved us hours every week. Highly recommend.",
    created_at: "2024-11-15",
    user: { id: "ru2", email: "", full_name: "Casey Brooks", avatar_url: "", role: "buyer", subscription: "pro", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "r3",
    user_id: "ru3",
    product_id: "1",
    rating: 4,
    comment: "Great product overall. The API is well-documented and easy to integrate. Would love to see more emotion control options.",
    created_at: "2024-11-10",
    user: { id: "ru3", email: "", full_name: "Riley Nguyen", avatar_url: "", role: "buyer", subscription: "free", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
  {
    id: "r4",
    user_id: "ru4",
    product_id: "1",
    rating: 5,
    comment: "The real-time streaming is a game changer. Sub-200ms latency for our live application. Worth every penny.",
    created_at: "2024-10-28",
    user: { id: "ru4", email: "", full_name: "Taylor Kim", avatar_url: "", role: "buyer", subscription: "starter", bio: "", website: "", stripe_customer_id: "", stripe_connect_id: "", created_at: "", updated_at: "" },
  },
];

export const categories = [
  "All",
  "Voice & Audio",
  "Image Generation",
  "Developer Tools",
  "Chatbots",
  "Agents",
  "Data & Analytics",
  "Language",
  "Writing",
  "Finance",
  "Productivity",
  "Computer Vision",
];

export const creatorNames: Record<string, string> = {
  c1: "NeuralVox Labs",
  c2: "OpenPixel Team",
  c3: "CodePilot Inc.",
  c4: "ChatWeaver AI",
  c5: "DataMind Analytics",
  c6: "TransLingua Foundation",
  c7: "MusicForge Studio",
  c8: "AgentSmith Corp",
  c9: "VisionAI Labs",
  c10: "WriteGenie HQ",
  c11: "FinanceBot Pro",
  c12: "DocuScan Team",
};
